// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // マイグレーションは常にローカルSQLiteで実行。
    // ランタイムはdb.tsのlibsqlアダプター経由でTursoに接続。
    url: "file:./dev.db",
  },
});
